title: Debdeep Paul
description: Personal website and blog of Debdeep Paul
url: "https://pauldebdeep9.github.io"
baseurl: ""
markdown: kramdown
permalink: /blog/:title/
timezone: Asia/Kolkata
future: true
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      nav: blog
